import type { GameModule } from "../types";
import { bindCommandListener } from "./registry";
import "./help";
import "./me";
import "./do";
import "./try";
import "./todo";
import "./b";
import "./s";
import "./w";
import "./stats";
import "./time";
import "./pass";
import "./lic";
import "./vbilet";
import "./medcard";
import "./selllic";
import "./hospital";
import "./gps";
import "./leaders";
import "./advokats";
import "./members";
import "./r";
import "./f";
import "./capture";
import "./makegun";
import "./sellgun";
import "./selldrug";
import "./d";
import "./gov";
import "./clear";
import "./su";
import "./wanted";
import "./limit";
import "./report";
import "./ads";
import "./home";
import "./heal";
import "./sellhouse";
import "./makestore";
import "./use";
import "./pay";
import "./find-id";
import "./mask";
import "./unmask";
import "./frisk";
import "./take";
import "./anim";
import { bindMenuDialogs } from "./mn";
import { bindGpsDialogs } from "../gps";
import { bindReportDialogs } from "./report";
import { bindOrgStaff } from "./org-staff";
import { bindSellLic } from "./selllic";
import { bindTimeLabels } from "./time";
import { bindPayLabels } from "./pay";
import { bindWantedDialogs } from "./wanted";
import { bindFindIdMarks } from "./find-id";
import { bindAds } from "./ads";
import { bindMedcardOffers } from "./medcard";
import { bindHelpDialogs } from "./help";
import { bindTakeDialogs } from "./take";
import { bindSellGunOffers } from "./sellgun";
import { bindSellDrugOffers } from "./selldrug";

export const commandsModule: GameModule = {
  name: "commands",
  start() {
    bindCommandListener();
    bindMenuDialogs();
    bindGpsDialogs();
    bindHelpDialogs();
    bindReportDialogs();
    bindOrgStaff();
    bindSellLic();
    bindTimeLabels();
    bindPayLabels();
    bindWantedDialogs();
    bindFindIdMarks();
    bindAds();
    bindMedcardOffers();
    bindTakeDialogs();
    bindSellGunOffers();
    bindSellDrugOffers();
  },
};
